// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LMS.Identity.DataModels;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using LMS.Identity.DataModels.Entities;
namespace LMS.Identity.DataModels.DataContext
{
    public partial class LMSDB_DevContext : DbContext
    {
        public LMSDB_DevContext()
        {
        }

        public LMSDB_DevContext(DbContextOptions<LMSDB_DevContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientPassword> ClientPassword { get; set; }
        public virtual DbSet<ClientStoreInfo> ClientStoreInfo { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerPassword> CustomerPassword { get; set; }
        public virtual DbSet<LoginAttempt> LoginAttempt { get; set; }
        public virtual DbSet<UserGender> UserGender { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=database.cqwxueaftokp.us-east-2.rds.amazonaws.com;Initial Catalog=LMSDB_Dev;Persist Security Info=True;User ID=admin;Password=mypassword");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<Client>(entity =>
            {
                entity.ToTable("Client", "Account");

                entity.Property(e => e.CompanyName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.Email)
                    .HasColumnName("EMail")
                    .HasMaxLength(50);

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.PhoneNumber).HasColumnName("phoneNumber");
            });

            modelBuilder.Entity<ClientPassword>(entity =>
            {
                entity.ToTable("ClientPassword", "Account");

                entity.Property(e => e.ClientId).HasColumnName("Client_id");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.Password)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<ClientStoreInfo>(entity =>
            {
                entity.ToTable("ClientStoreInfo", "Account");

                entity.Property(e => e.ClientId).HasColumnName("Client_id");

                entity.Property(e => e.ClientStoreCode)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<Customer>(entity =>
            {
                entity.ToTable("Customer", "Account");

                entity.Property(e => e.CustomerId).HasColumnName("Customer_id");

                entity.Property(e => e.Address1).HasMaxLength(50);

                entity.Property(e => e.Address2).HasMaxLength(50);

                entity.Property(e => e.City).HasMaxLength(50);

                entity.Property(e => e.Country).HasMaxLength(50);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.CustomerGenderId).HasColumnName("CustomerGenderID");

                entity.Property(e => e.CustomerName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Email)
                    .HasColumnName("EMail")
                    .HasMaxLength(50);

                entity.Property(e => e.FamilyName).HasMaxLength(100);

                entity.Property(e => e.MiddleName).HasMaxLength(100);

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.PhoneNumber).HasColumnName("phoneNumber");

                entity.Property(e => e.Region).HasMaxLength(50);

                entity.Property(e => e.Zip).HasMaxLength(10);

                entity.HasOne(d => d.CustomerGender)
                    .WithMany(p => p.Customer)
                    .HasForeignKey(d => d.CustomerGenderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Customer__Custom__5EBF139D");
            });

            modelBuilder.Entity<CustomerPassword>(entity =>
            {
                entity.HasKey(e => e.PasswordId)
                    .HasName("PK__Customer__850F2032BB57A3A3");

                entity.ToTable("CustomerPassword", "Account");

                entity.Property(e => e.PasswordId).HasColumnName("Password_id");

                entity.Property(e => e.ClientId).HasColumnName("Client_id");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.Password).HasMaxLength(50);

                entity.Property(e => e.PasswordAnswer).HasMaxLength(50);

                entity.Property(e => e.PasswordQuestion).HasMaxLength(50);
            });

            modelBuilder.Entity<LoginAttempt>(entity =>
            {
                entity.ToTable("LoginAttempt", "Account");

                entity.Property(e => e.LoginAttemptId).HasColumnName("LoginAttemptID");

                entity.Property(e => e.BrowserType).HasMaxLength(200);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.Ipnumber)
                    .HasColumnName("IPNumber")
                    .HasMaxLength(50);

                entity.Property(e => e.Password).HasMaxLength(50);

                entity.Property(e => e.UserName).HasMaxLength(50);
            });

            modelBuilder.Entity<UserGender>(entity =>
            {
                entity.ToTable("UserGender", "Account");

                entity.Property(e => e.GenderName)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}