// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace LMS.Identity.DataModels.Entities
{
    public partial class ClientStoreInfo
    {
        public int Id { get; set; }
        public int? ClientId { get; set; }
        public string ClientStoreCode { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? ModifiedByUserId { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}