// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace LMS.Identity.DataModels.Entities
{
    public partial class ClientPassword
    {
        public int Id { get; set; }
        public int? ClientId { get; set; }
        public string Password { get; set; }
        public bool? Active { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? ModifiedByUserId { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}