// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace LMS.Identity.DataModels.Entities
{
    public partial class UserGender
    {
        public UserGender()
        {
            Customer = new HashSet<Customer>();
        }

        public int UserGenderId { get; set; }
        public string GenderName { get; set; }

        public virtual ICollection<Customer> Customer { get; set; }
    }
}