// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace LMS.Identity.DataModels
{
    public partial class LoginAttempt
    {
        public int LoginAttemptId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Ipnumber { get; set; }
        public string BrowserType { get; set; }
        public bool? Success { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}