// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace LMS.Identity.DataModels
{
    public partial class Password
    {
        public int PasswordId { get; set; }
        public int? UserId { get; set; }
        public string Password1 { get; set; }
        public string PasswordAnswer { get; set; }
        public string PasswordQuestion { get; set; }
        public bool? Active { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? ModifiedByUserId { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}