// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace LMS.Identity.DataModels
{
    public partial class UserGender
    {
        public UserGender()
        {
            Client = new HashSet<Client>();
        }

        public int UserGenderId { get; set; }
        public string GenderName { get; set; }

        public virtual ICollection<Client> Client { get; set; }
    }
}