<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\**" />
    <EmbeddedResource Remove="Common\**" />
    <None Remove="Common\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LMS.Core.Repository\LMS.Core.Repository.csproj" />
    <ProjectReference Include="..\LMS.Master.DTO\LMS.Master.DTO.csproj" />
  </ItemGroup>

</Project>
