// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LMS.Master.DataModels;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using LMS.Master.DataModels.Entities;
namespace LMS.Master.DataModels.DataContext
{
    public partial class LMS_Master_DevContext : DbContext
    {
        public LMS_Master_DevContext()
        {
        }

        public LMS_Master_DevContext(DbContextOptions<LMS_Master_DevContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LaundryServices> LaundryServices { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=database.cqwxueaftokp.us-east-2.rds.amazonaws.com;Initial Catalog=LMS_Master_Dev;Persist Security Info=True;User ID=admin;Password=mypassword");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<LaundryServices>(entity =>
            {
                entity.ToTable("LaundryServices", "Master");

                entity.Property(e => e.ClientStoreCode)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.ServiceCode)
                    .IsRequired()
                    .HasMaxLength(10);

                entity.Property(e => e.ServiceName)
                    .IsRequired()
                    .HasMaxLength(15);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}