// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LMS.Master.DataModels;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using LMS.Master.DataModels.Entities;
namespace LMS.Master.DataModels.DataContext
{
    public partial class LMS_Master_DevContext : DbContext
    {
        public LMS_Master_DevContext()
        {
        }

        public LMS_Master_DevContext(DbContextOptions<LMS_Master_DevContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AvailableLaundryCustomerTypesForClient> AvailableLaundryCustomerTypesForClient { get; set; }
        public virtual DbSet<AvailableLaundryServicesForClient> AvailableLaundryServicesForClient { get; set; }
        public virtual DbSet<LaundryCustomerItemBrands> LaundryCustomerItemBrands { get; set; }
        public virtual DbSet<LaundryCustomerItemsByType> LaundryCustomerItemsByType { get; set; }
        public virtual DbSet<LaundryCustomerServices> LaundryCustomerServices { get; set; }
        public virtual DbSet<LaundryCustomerTypes> LaundryCustomerTypes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=database.cqwxueaftokp.us-east-2.rds.amazonaws.com;Initial Catalog=LMS_Master_Dev;User ID=admin;Password=mypassword");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<AvailableLaundryCustomerTypesForClient>(entity =>
            {
                entity.ToTable("AvailableLaundryCustomerTypesForClient", "Master");

                entity.Property(e => e.ClientStoreCode)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.CustomerTypeName)
                    .IsRequired()
                    .HasMaxLength(15);

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<AvailableLaundryServicesForClient>(entity =>
            {
                entity.ToTable("AvailableLaundryServicesForClient", "Master");

                entity.Property(e => e.ClientStoreCode)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.CustomerServiceType)
                    .IsRequired()
                    .HasMaxLength(15);

                entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LaundryCustomerItemBrands>(entity =>
            {
                entity.ToTable("laundryCustomerItemBrands", "Master");

                entity.Property(e => e.ItemBrandType)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<LaundryCustomerItemsByType>(entity =>
            {
                entity.ToTable("laundryCustomerItemsByType", "Master");

                entity.Property(e => e.ItemType)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<LaundryCustomerServices>(entity =>
            {
                entity.ToTable("LaundryCustomerServices", "Master");

                entity.Property(e => e.CustomerServiceType)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<LaundryCustomerTypes>(entity =>
            {
                entity.ToTable("LaundryCustomerTypes", "Master");

                entity.Property(e => e.CustomerTypeName)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}