// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace LMS.Master.DataModels.Entities
{
    public partial class AvailableLaundryServicesForClient
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string ClientStoreCode { get; set; }
        public int CustomerServiceTypeId { get; set; }
        public string CustomerServiceType { get; set; }
        public int CreatedByUserId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int ModifiedByUserId { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}