// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace LMS.Master.DataModels.Entities
{
    public partial class LaundryCustomerItemBrands
    {
        public int Id { get; set; }
        public string ItemBrandType { get; set; }
    }
}